---

- name: "update apt packages"
  become: yes
  apt:
    update_cache: yes

- name: "upgrade"
  become: yes
  apt:
    upgrade: yes

- name: remove dependencies that are no longer required
  become: true
  apt:
    autoremove: yes

- name: "Install dependencies"
  become: yes
  apt:
    name: ['nodejs', 'npm']
    update_cache: yes

- name: "Install pm2"
  become: yes
  npm:
    name: pm2
    global: yes
    production: yes
    state: present