---

- name: "Unarchive backend files"
  unarchive:
    src: artifact.tar.gz
    dest: .

- name: "executing node app with pm2"
  shell: |
    npm install
    pm2 stop default
    pm2 start npm -- start